// JavaScript Document
document.writeln("<div class=\"zfgkmm\">");
document.writeln("    <a href=\"\/affair\/ldzc\">领导班子<\/a>");
document.writeln("    <a href=\"\/affair\/govintro\/index_jg.html\">机构职能<\/a>");
//document.writeln("    <a href=\"\/affair\/fwcn/\">服务承诺<\/a>");
document.writeln("    <a href=\"\/affair\/announcement\">政府公告<\/a>");
document.writeln("    <a href=\"\/affair\/file\">政策文件<\/a>");
document.writeln("    <a href=\"\/affair\/ghjh/\">规划计划<\/a>");
document.writeln("    <a href=\"\/affair\/tjxx/\">统计信息<\/a>");
document.writeln("    <a href=\"\/affair\/caizhengsz\/\">财政收支<\/a>");
document.writeln("    <a href=\"\/affair\/zfcg\/\">政府采购<\/a>");
document.writeln("    <a href=\"\/affair\/zdxm\">重大项目<\/a>");
document.writeln("    <a href=\"\/affair\/domain\/\">重点领域<\/a>");
document.writeln("    <a href=\"\/affair\/yjglnew\/\">应急管理<\/a>");
document.writeln("    <a href=\"\/affair\/civilemployed\/zkzp\">人事信息<\/a>   ");
document.writeln("    <a href=\"\/dynamic\/newspe\/chyqlqd\">权责清单<\/a>   ");
document.writeln("    <a href=\"http:\/\/www.bjchy.gov.cn/robot/shuanggongshi.xz_cf.do?m=showCfUnit\">双公示信息<\/a>");
document.writeln("    <a href=\"\/affair\/xzjcssj\/index_ssjygk.html\">双随机一公开<\/a>");
document.writeln("    <a style=\"width:100px\" href=\"\/gsxx_xzzf.html\">行政执法信息公示<\/a>");
document.writeln("    <a style=\"width:100px\" href=\"\/affair/zfdwlxdh/\">咨询联系电话<\/a>");
document.writeln("    <a style=\"width:80px\" href=\"\/affair/yiqingfk/zxxx\">疫情防控<\/a>");
document.writeln("    <div class=\"clear\"><\/div>");
document.writeln("    <\/div>");
//document.writeln("<div class=\"zfgkmm\">");
//document.writeln("      <ol>");
//document.writeln("        <li><a href=\"\/affair\/ldzc\/\" target=\"_blank\"><i><img src=\"\/resource\/images\/syzw01.png\"><\/i>领导班子<\/a><\/li>");
//document.writeln("        <li><a href=\"\/affair\/file\/zhcfb\/\" target=\"_blank\"><i><img src=\"\/resource\/images\/syzw02.png\"><\/i>政策文件<\/a><\/li>");
//document.writeln("        <li><a href=\"\/affair\/govintro\/\" target=\"_blank\"><i><img src=\"\/resource\/images\/syzw03.png\"><\/i>机构职能<\/a><\/li>");
//document.writeln("        <li><a href=\"\/affair\/caizhengsz\/\" target=\"_blank\"><i><img src=\"\/resource\/images\/syzw04.png\"><\/i>财政收支<\/a><\/li>");
//document.writeln("        <li><a href=\"\/affair\/fwcn\/\" target=\"_blank\"><i><img src=\"\/resource\/images\/syzw05.png\"><\/i>服务承诺<\/a><\/li>");
//document.writeln("        <li><a href=\"\/affair\/sfbz\/\" target=\"_blank\"><i><img src=\"\/resource\/images\/syzw06.png\"><\/i>收费标准<\/a><\/li>");
//document.writeln("        <li><a href=\"\/affair\/zfgk\/\" target=\"_blank\"><i><img src=\"\/resource\/images\/syzw07.png\"><\/i>政府公开<\/a><\/li>");
//document.writeln("        <li><a href=\"\/gsxx.html\" target=\"_blank\"><i><img src=\"\/resource\/images\/syzw08.png\"><\/i>双公示信息<\/a><\/li>");
//document.writeln("      <\/ol>");
//document.writeln("    <\/div>");